Feature parser
Mazomenos/Flexlogic_Onboarding pull request #5
Opened 2024-05-14 23:30 UTC by danielaruiz1

2024-05-16 20:57 UTC, NovoxMx approved these changes
Approved, everything seems to be in order.

2024-05-17 01:21 UTC, Jaza2401 commented on src/libs/X12parser/lib/parserTestClient.md
No se que tan buena idea sea tener funcionalidad de servidor en un componente cliente, pero esta bien lo demas

2024-05-17 01:26 UTC, Jaza2401 requested changes
Unas dudas con el codigo

2024-05-17 01:26 UTC, Jaza2401 commented on next.config.mjs
Pusiste esto tu o se genero solo?

2024-05-17 01:26 UTC, Jaza2401 commented on src/app/api/tests/uploadEDI.ts
Por que lo comentaste? Si no se usa borralo

2024-05-17 01:26 UTC, Jaza2401 commented on src/app/page.tsx
El boton es necesario? Igual ya se esta importando el componente ParserTest, fuera de eso tdbn

2024-05-17 23:34 UTC, Jaza2401 approved these changes
Looks good to me

2024-05-20 21:09 UTC, merged